name: "COLT - Ontology to Code Library"
description: "Goes through ontology files and generates a code library to access them programatically."
inputs:
  from:
    description: "The directory with the ontologies you wish to transform."
    required: true
    default: "."
  to:
    description: "The directory where you wish to place the generated code library (this directory will be emptied and filled with new content)."
    required: true
    default: "./colt/"
  package_name:
    description: "The name of the code library package generated."
    required: false
  namespace:
    description: "The namespace for the C# project generated."
    required: false
    default: "Auto.Ontology"
  dotnet:
    description: "The version of .NET to use. 6, 7, and 8 are supported."
    required: false
    default: "8"
runs:
  using: "docker"
  image: "Dockerfile"