name: Colt
on:
    pull_request:

jobs:
    ontology_transformer:
        runs-on: ubuntu-latest
        name: Colt
        permissions:
            pull-requests: write
            contents: write
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
            - name: Colt
              id: colt
              uses: equinor/colt@init

            